export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ADD_TO_BROWSED_MOVIES = 'ADD_TO_BROWSED_MOVIES'
export const ADD_MOVIE_TO_FAVORITE = 'ADD_MOVIE_TO_FAVORITE'
export const REMOVE_MOVIE_FROM_FAVORITE = 'REMOVE_MOVIE_FROM_FAVORITES'
export const GET_FAVORITE_MOVIES = 'GET_FAVORITE_MOVIES'
